### ISSUE TITLE
Error while saving file

### ISSUE THREAD

**Issue by IAmUnbounded** [zhanghang1989/Deep-Encoding#1]
The model generates an error while saving the file:
write error: wrote 8269040 blocks instead of 8388608 at /tmp/luarocks_torch-scm-1-3604/torch7/lib/TH/THDiskFile.c:356

How can this be resolved ?

**Comment by zhanghang1989** [comment]
This looks wired. Can you try to download the repo and do `luarocks install` locally

**Comment by IAmUnbounded** [comment]
Thanks, I solved the issue. Something was wrong with my system. I wanted to know, where are the extracted features from the images stored which can be further used for some classification?
