### ISSUE TITLE
Extracting features

### ISSUE THREAD

**Issue by IAmUnbounded** [zhanghang1989/Deep-Encoding#2]
How can I extract features or encoding for my own dataset and get them saved in a file?

**Comment by zhanghang1989** [comment]
Please see the example:
https://github.com/cvondrick/torch-feature-extract/blob/master/extract_simple.lua#L86~L102

**Comment by IAmUnbounded** [comment]
I want to extract texture features. Will this model extract features that could be used for texture classification?

**Comment by zhanghang1989** [comment]
Yes, but you need to train the model first.

**Comment by IAmUnbounded** [comment]
yes, which file should I run for that?

**Comment by zhanghang1989** [comment]
You can write your own code similar to the example:
https://github.com/cvondrick/torch-feature-extract/blob/master/extract_simple.lua#L86~L102

**Comment by IAmUnbounded** [comment]
okay, thank you so much.
