### ISSUE TITLE
training model

### ISSUE THREAD

**Issue by IAmUnbounded** [zhanghang1989/Deep-Encoding#3]
What should be the format of dataset and image sizes to train my own network for texture classification?

**Comment by zhanghang1989** [comment]
For training detail, please refer to the paper https://arxiv.org/pdf/1612.02844v1.pdf

**Comment by IAmUnbounded** [comment]
the paper discusses results on 5 datasets, but how can I train this on a dataset created by me for classification of textures and what changes have to be implemented accordingly in the code?

**Comment by zhanghang1989** [comment]
For your own experiment settings, please discuss with your coauthors.
